#!/bin/sh
# Build the dictionary

RESOURCES=src/main/resources/de/danielnaber/jwordsplitter
TXT_FILE=$RESOURCES/wordsGerman.txt

echo "Removing $TXT_FILE"
rm $TXT_FILE

echo "# DO NOT EDIT -- File generated by build.sh" >$TXT_FILE
echo -n "# " >>$TXT_FILE
date >>$TXT_FILE
grep -v -f $RESOURCES/removals.txt $RESOURCES/languagetool-dict.txt | cat - $RESOURCES/additions.txt $RESOURCES/germanPrefixes.txt | grep -v "^#" >>$TXT_FILE

#mvn clean package
echo "Writing new file to: $TXT_FILE"
echo -n "Result: "
ls -l $TXT_FILE

echo -n "Total lines: "
wc -l $TXT_FILE
